### ISSUE TITLE
Packing problem with my custom scenario

### ISSUE THREAD

**Issue by geevargs** [orig74/UE4PyhtonBridge#2]
I followed the instructions for packaging the custom scenario for the PX4_gazebo demo.
It deosnt trigger the unreal images.
![image](https://user-images.githubusercontent.com/29235421/32083932-28118432-ba7b-11e7-8b35-0135b382cc7d.png)

**Comment by orig74** [comment]
Just to make sure I understand,
When you run with GAME_PATH = /DroneLab/baked_games/game_demo/LinuxNoEditor/
it is working fine and when you run it with:
 GAME_PATH =  /DroneLab/baked_games/<your game> /LinuxNoEditor/ 
it is not working?

**Comment by geevargs** [comment]
![image](https://user-images.githubusercontent.com/29235421/32116353-2b87f7c0-baff-11e7-89bf-3ae6372c1bc3.png)

**Comment by geevargs** [comment]
When I run the normal demo it shows the main standalone game and doesn't show me the 2 otherimages called the rgb_camera_0 and the rgb depth camera.When I use my path it shows the other two camera's but no images inside the window.

**Comment by orig74** [comment]
It needs to open an unreal engine game window look at this demo:
https://www.youtube.com/watch?v=vCCAboWWReo
this is what supposed to happen. If you don't see the game window then something is wrong and images won't be sent to the other window in the simulation. 

there are two windows in the tmux terminal 
0- for the simulated drone and ROS
1- for the unreal game
show me the output of the unreal game (you can navigate between the windows using ctrl-b n)

**Comment by geevargs** [comment]
The unreal screen shows up but no other windows pop up.
![screenshot from 2017-11-01 12_17_14](https://user-images.githubusercontent.com/29235421/32298105-89470992-bf0e-11e7-9bb4-7fb49b9fd17a.png)

**Comment by geevargs** [comment]
I have the same problem with my two drones version of the same thing.

**Comment by geevargs** [comment]
During the packing process,the pyinit is not defined function .

![screenshot from 2017-11-14 15 47 40](https://user-images.githubusercontent.com/29235421/32811224-6e8e1380-c953-11e7-8128-68dcb40b637a.png)

**Comment by geevargs** [comment]
I couldnt scroll and see what was causing the error.

**Comment by orig74** [comment]
do you git it after creating the packed game and trying to run using run_game.sh?

**Comment by geevargs** [comment]
yes...so when I use ctrl b-n and see the unreal engine screen it shows this error and I cant debug it.

**Comment by orig74** [comment]
you need to run the set_path.py for the baked game
run 

> set_path.py -h

for help

**Comment by geevargs** [comment]
![screenshot from 2017-11-16 13 06 49](https://user-images.githubusercontent.com/29235421/32915818-07255492-cacf-11e7-9307-eb957e957d03.png)

**Comment by geevargs** [comment]
I tried the ctrl-b n and then did the ctrl -c and the ctrl-b ] didnt really work
![screenshot from 2017-11-16 13 33 33](https://user-images.githubusercontent.com/29235421/32917189-3dec2434-cad3-11e7-8a7a-85b2f4a38d3c.png)

**Comment by orig74** [comment]
you can hit the up key or just run ./run.bat again and immediately after you see the error hit ctrl-c again.
