### ISSUE TITLE
I am getting this error when I initiate unreal engine scenario.

### ISSUE THREAD

**Issue by geevargs** [orig74/UE4PyhtonBridge#3]
![image](https://user-images.githubusercontent.com/29235421/33585676-49c2cc04-d91a-11e7-9e7b-a74861b7d9ab.png)

**Comment by geevargs** [comment]
I am trying to setup a connection between FDM with a external IP address and I just need the UE4pyhton bridge to get that data using unrealproxy.

**Comment by geevargs** [comment]
I already get data from an external IP address.
![image](https://user-images.githubusercontent.com/29235421/33586273-7c5f6444-d91d-11e7-9345-2c253d66c310.png)

**Comment by orig74** [comment]
Hi, 
The fastest way is to forward the connection using something like socat and running it on the host.
take a look at this link: https://www.cyberciti.biz/faq/linux-unix-tcp-port-forwarding/
hopefully, it will work.
