### ISSUE TITLE
Packaging issue unable to establish proper pyserver with custom baked game

### ISSUE THREAD

**Issue by geevargs** [orig74/UE4PyhtonBridge#4]
![screenshot from 2018-03-19 13 18 01](https://user-images.githubusercontent.com/29235421/37619926-0e21ce9c-2b78-11e8-99db-a93dd13b81c4.png)

**Comment by geevargs** [comment]
I am try to establish the pyserver bridge and it gives the error Wrapper module not found ....after I followed all the procedures for the packaging as mentioned in the wiki.
I had written a similar one before but didnt find a proper solution.
I am not using any demo but just need to use the FDM  and unreal proxy to send telemetry data to unreal engine.

**Comment by geevargs** [comment]
Linux 14.04
GTX 1080 Ti
Normal FDM works perfectly....
main error : 
 Play

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'Wrappers'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pyinit' is not defined
[2018.03.19-20.16.17:569][  0]r.CustomDepth = "3"

[MyProject2-backup-2018.03.19-13.16.08.log](https://github.com/orig74/UE4PyhtonBridge/files/1826822/MyProject2-backup-2018.03.19-13.16.08.log)

**Comment by geevargs** [comment]
![image](https://user-images.githubusercontent.com/29235421/37629088-f3bc5974-2b99-11e8-9724-b80110fbb5ca.png)

**Comment by orig74** [comment]
This is probably due to wrong set_path.sh setup.
please send as an attachment the tmux scripts you are using for the packed game

**Comment by geevargs** [comment]
[Airspace1.txt](https://github.com/orig74/UE4PyhtonBridge/files/1830532/Airspace1.txt)

**Comment by orig74** [comment]
Hi,
The paths setting are wrong in this file. Take a look at runtmux_game_docker.sh in the px4_gazebo demo as a reference. The GAME_PATH needs to be to internal docker path and not the system host path

**Comment by geevargs** [comment]
I am trying to use a system host path...because the only thing i need is the FDM input...I am trying to do it in system host...it works for normal unreal engine  software with no issues at all...I need it to work the same way for the game binary...

**Comment by orig74** [comment]
in that case take a look at the run.sh (should be inside your packed game directory) file created by the set_path script and make sure that all the paths inside the run.sh exists

**Comment by geevargs** [comment]
I got the set_path.py  to create the run.sh in my binary game 
The error right now:
start loading lib file
done loading lib file
pyinit imported
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sujith/DroneSimLab/UE4PyhtonBridge/src/Wrappers/pyinit.py", line 7, in <module>
    from Wrappers import entry_point
  File "/home/sujith/DroneSimLab/UE4PyhtonBridge/src/Wrappers/entry_point.py", line 4, in <module>
    exec("import "+os.environ['BRIDGE_ENTRY_NAME']+" as main_module")
  File "<string>", line 1, in <module>
ImportError: No module named 'unreal_proxy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pyinit' is not defined

[run.txt](https://github.com/orig74/UE4PyhtonBridge/files/1831293/run.txt)

**Comment by geevargs** [comment]
I fixed it...path error to unreal_proxy

**Comment by orig74** [comment]
nice!
